# Generated by Django 4.2.3 on 2023-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('first_name', models.TextField(null=True)),
                ('birthdate', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
