# Generated by Django 4.2.3 on 2023-07-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_object', models.TextField()),
                ('content', models.TextField()),
                ('action_date', models.DateTimeField()),
                ('state', models.IntegerField(choices=[(0, 'Not Read'), (1, 'Read'), (2, 'Deleted')])),
                ('is_spam', models.IntegerField(choices=[(0, 'Not Spam'), (1, 'Spam')])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mails', to='app.users')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to='app.users')),
            ],
        ),
    ]
